### ISSUE TITLE
Require ESM 

### ISSUE THREAD

**Issue by alxpereira** [belladoreai/llama3-tokenizer-js#2]
Hello, 

I have a pb importing the lib, got the following issue when instantiated

```Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/alexandrepereira/Documents/@Dev/@2501/2501-engine/node_modules/llama3-tokenizer-js/llama-tokenizer.js```

```ts
import llama3Tokenizer from "llama3-tokenizer-js";
...etc
```

tsconfig
```ts
"compilerOptions": {
      "module": "commonjs",
      "esModuleInterop": true,
      "target": "es6",
      "sourceMap": true,
      "strictNullChecks": true,
      "outDir": "dist",
      "noEmit": true
  },
```

Thanks!

**Comment by belladoreai** [comment]
It looks like your repo is using CommonJS?

In that case, try this alternative way of importing:

```
async function main() {
    const llama3Tokenizer = await import('llama3-tokenizer-js')
    console.log(llama3Tokenizer.default.encode("Hello world!").length)
}

main();
```

**Comment by belladoreai** [comment]
I'm gonna close this as I didn't hear back from you, but if you are still having problems importing this lib, just send a message and I'll help you with it.
