### ISSUE TITLE
Chat Template Tokenization?

### ISSUE THREAD

**Issue by yildize** [belladoreai/llama3-tokenizer-js#6]
Hello there, can we use the library for tokenizing a chat template (messages consisting of system, user and assistant)? 

Thanks in advance :)

**Comment by belladoreai** [comment]
Hi, yes you can use the library for this purpose. The easiest way would be to take a string representation of the chat template with the messages included, and just tokenizing that. Alternatively, you can write your own code which tokenizes each part of the template separately and combines them, adding special tokens as needed.
