### ISSUE TITLE
Publish commonjs compatibility

### ISSUE THREAD

**Issue by magJ** [belladoreai/llama3-tokenizer-js#9]
I see that you added commonjs support, however, it looks like these changes aren't published to any released version yet.

Could you please publish a version with the commonjs support?

**Comment by belladoreai** [comment]
The file that you are thinking of was added for a very particular use case requested by a user.

For most CommonJS users it should be sufficient to just use the normal bundle like this:

```
async function main() {
    const llama3Tokenizer = await import('llama3-tokenizer-js')
    console.log(llama3Tokenizer.default.encode("Hello world!").length)
}

main();
```

But I will make a new release anyway, in case it helps.

**Comment by magJ** [comment]
Thanks!

> For most CommonJS users it should be sufficient to just use the normal bundle like this

NodeJS requires `--experimental-vm-modules` for dynamic imports to work, and it's just not feasible to enable that flag in our codebase.

The new version works.
Importing it is still a bit hacky, but I'm not complaining.

For anyone else reading and using typescript:

```ts
import type { Llama3Tokenizer } from 'llama3-tokenizer-js'
// @ts-ignore
import { loadLlama3Tokenizer } from 'llama3-tokenizer-js/bundle/commonjs-llama3-tokenizer-with-baked-data'
const llama3Tokenizer = loadLlama3Tokenizer() as Llama3Tokenizer
```

**Comment by magJ** [comment]
> New release 1.1.4 published.

Thanks!

> For most CommonJS users it should be sufficient to just use the normal bundle like this

NodeJS with jest requires `--experimental-vm-modules` for dynamic imports to work, and it's just not feasible to enable that flag in our codebase.

Unfortunately it looks like I can't import the commonjs bundle.


```
Error [ERR_REQUIRE_ESM]: require() of ES Module /myproject/node_modules/llama3-tokenizer-js/bundle/commonjs-llama3-tokenizer-with-baked-data.js from /myproject/src/tokenizer.ts not supported.
commonjs-llama3-tokenizer-with-baked-data.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename commonjs-llama3-tokenizer-with-baked-data.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /myproject/node_modules/llama3-tokenizer-js/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

I guess without making any major changes to the project, it would have to be named `.cjs`


In the mean time, I've just vendored the commonjs file into my codebase.


<sup>Note: I deleted an earlier version of this comment, where I claimed the new version worked, after I failed to test it properly</sup>

**Comment by belladoreai** [comment]
I didn't want to rename the CommonJS bundle, because the other person who asked for it earlier may be relying on the filepath to not change. So I have now changed the create-bundle script such that it writes the same CommonJS bundle into 2 files, one named .js and one named .cjs. Try if you can now load the .cjs file properly?
